package ${packageName};

/**
* Enumeration for ${enumClass} values.
* Generated by EasyBase Code Generator.
*/
public enum ${enumClass} {
<#list enumValues as value>
${value}<#if value_has_next>,</#if>
</#list>
}