-- Migration script for Product
-- Generated by EasyBase Code Generator

CREATE TABLE eb_product (
    id VARCHAR(36),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000),
    price DOUBLE PRECISION NOT NULL,
    sku VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(50),

    -- Audit fields
    created_date TIMESTAMP,
        last_modified_date TIMESTAMP,
        created_by VARCHAR(255),
        last_modified_by VARCHAR(255),
        version BIGINT DEFAULT 0,

    -- Soft delete field
    deleted BOOLEAN DEFAULT FALSE
);

-- Create indexes
        CREATE UNIQUE INDEX idx_eb_product_sku ON eb_product(sku);

                CREATE INDEX idx_eb_product_name ON eb_product(name);

