package com.easybase.user.model;

import java.util.UUID;
import java.time.Instant;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import com.easybase.department.model.Department;
import com.easybase.user.model.enums.UserStatus;

/**
* Interface defining the User entity.
* Generated by EasyBase Code Generator.
*/
public interface User {
    UUID getId();
    void setId(UUID id);

    String getEmail();
    void setEmail(String email);

    String getFirstName();
    void setFirstName(String firstName);

    String getLastName();
    void setLastName(String lastName);

    UserStatus getStatus();
    void setStatus(UserStatus status);

    Department getDepartment();
    void setDepartment(Department department);

}