package com.easybase.user.model;

import java.util.UUID;
import com.easybase.user.model.enums.UserStatus;
import com.easybase.department.model.Department;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Component;

/**
* Wrapper for User implementations that provides method interception.
* This class can be used to add functionality like logging, validation, or
* security checks around entity methods.
*
* Generated by EasyBase Code Generator.
*/
@Component
@Primary
public class UserWrapper implements User {

private final User delegate;

@Autowired
public UserWrapper(UserImpl delegate) {
this.delegate = delegate;
    }

    @Override
    public UUID getId() {
// Pre-processing could be added here
UUID result = delegate.getId();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setId(UUID id) {
// Pre-processing could be added here
delegate.setId(id);
        // Post-processing could be added here
    }

    @Override
    public String getEmail() {
// Pre-processing could be added here
String result = delegate.getEmail();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setEmail(String email) {
// Pre-processing could be added here
delegate.setEmail(email);
        // Post-processing could be added here
    }

    @Override
    public String getFirstName() {
// Pre-processing could be added here
String result = delegate.getFirstName();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setFirstName(String firstName) {
// Pre-processing could be added here
delegate.setFirstName(firstName);
        // Post-processing could be added here
    }

    @Override
    public String getLastName() {
// Pre-processing could be added here
String result = delegate.getLastName();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setLastName(String lastName) {
// Pre-processing could be added here
delegate.setLastName(lastName);
        // Post-processing could be added here
    }

    @Override
    public UserStatus getStatus() {
// Pre-processing could be added here
UserStatus result = delegate.getStatus();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setStatus(UserStatus status) {
// Pre-processing could be added here
delegate.setStatus(status);
        // Post-processing could be added here
    }

    @Override
    public Department getDepartment() {
// Pre-processing could be added here
Department result = delegate.getDepartment();
        // Post-processing could be added here
        return result;
    }

    @Override
    public void setDepartment(Department department) {
// Pre-processing could be added here
delegate.setDepartment(department);
        // Post-processing could be added here
    }

}