package com.easybase.user.repository;

import com.easybase.user.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import com.easybase.user.model.enums.UserStatus;
import com.easybase.department.model.Department;

/**
* Repository for User entities.
* Generated by EasyBase Code Generator.
*/
@Repository
public interface UserRepository extends JpaRepository<User, UUID> {
List<User> findByEmailAndStatus(String email, UserStatus status);
List<User> findByDepartmentId(UUID departmentId);
Long countByDepartmentId(UUID departmentId);
}