package ${entity.baseComponentPackage("service")};

import ${entity.componentPackage("model")}.${entity.name};
import ${entity.componentPackage("api")}.model.dto.${entity.name}DTO;
import ${entity.componentPackage("api")}.model.dto.${entity.name}RequestDTO;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import java.util.List;
import java.util.Optional;
<#assign primaryKey = entity.primaryKey>
<#if primaryKey?has_content>
    import ${primaryKey.get().javaType};
</#if>

/**
* Base local service interface for ${entity.name}.
* Generated by EasyBase Code Generator.
*/
public interface ${entity.name}BaseLocalService {
/**
* Creates a new ${entity.name}.
*
* @param requestDTO the request DTO
* @return the created DTO
*/
${entity.name}DTO create(${entity.name}RequestDTO requestDTO);

/**
* Updates an existing ${entity.name}.
*
* @param id the ID
* @param requestDTO the request DTO
* @return the updated DTO
*/
${entity.name}DTO update(<#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if> id, ${entity.name}RequestDTO requestDTO);

/**
* Retrieves a ${entity.name} by ID.
*
* @param id the ID
* @return the DTO, if found
*/
Optional<${entity.name}DTO> findById(<#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if> id);

    /**
    * Retrieves all ${entity.name} entities with pagination.
    *
    * @param pageable the pagination information
    * @return a page of DTOs
    */
    Page<${entity.name}DTO> findAll(Pageable pageable);

        /**
        * Deletes a ${entity.name} by ID.
        *
        * @param id the ID
        * @return true if deleted, false otherwise
        */
        boolean delete(<#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if> id);

        <#if entity.isSoftDeleteEnabled()>
            /**
            * Permanently deletes a ${entity.name} by ID.
            *
            * @param id the ID
            * @return true if deleted, false otherwise
            */
            boolean hardDelete(<#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if> id);
        </#if>

        /**
        * Searches for ${entity.name} entities.
        *
        * @param search the search query
        * @param filter the filter query
        * @param sort the sort expression
        * @param pageable the pagination information
        * @return a page of DTOs
        */
        Page<${entity.name}DTO> search(String search, String filter, String sort, Pageable pageable);

            <#list entity.finders as finder>
                /**
                * ${finder.name} finder method.
                */
            <#-- Using the method call correctly -->
                <#assign methodSignatureStr = finder.getMethodSignature()>
                <#assign entityName = entity.name>
                <#assign replacedSignature = methodSignatureStr?replace(entityName, entityName + "DTO")>
                ${replacedSignature};
            </#list>
            }