package com.example.product.api.base.model.dto;

import java.time.Instant;

/**
* Response DTO for Product.
* Generated by EasyBase Code Generator.
*/
public class ProductResponseDTO extends ProductBaseDTO {
// Additional response-specific fields can be added here

// CUSTOM CODE START: fields
// Add custom fields here
// CUSTOM CODE END: fields

// CUSTOM CODE START: methods
// Add custom methods here
// CUSTOM CODE END: methods
}