package com.example.product.api.base.model.dto;

    import java.util.UUID;
    import jakarta.validation.constraints.NotBlank;
    import jakarta.validation.constraints.Size;
    import jakarta.validation.constraints.NotNull;
    import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.*;

/**
* Request DTO for creating or updating a Product.
* Generated by EasyBase Code Generator.
*/
public class ProductRequestDTO {
            @NotBlank
            @Size(max = 255)
        private String name;
        private String description;
            @NotNull
            @Min(value = 0)
        private Double price;
            @NotBlank
        private String sku;
        private ProductStatus status;

// Getters and setters
        public String getName() {
        return name;
        }

        public void setName(String name) {
        this.name = name;
        }
        public String getDescription() {
        return description;
        }

        public void setDescription(String description) {
        this.description = description;
        }
        public Double getPrice() {
        return price;
        }

        public void setPrice(Double price) {
        this.price = price;
        }
        public String getSku() {
        return sku;
        }

        public void setSku(String sku) {
        this.sku = sku;
        }
        public ProductStatus getStatus() {
        return status;
        }

        public void setStatus(ProductStatus status) {
        this.status = status;
        }
}