package com.example.product.model.enums;

/**
* Enumeration of ProductStatus values.
* Generated by EasyBase Code Generator.
*/
public enum ProductStatus {
    ACTIVE,
    INACTIVE,
    DISCONTINUED;
}