package com.easybase.user.web.dto;

import jakarta.validation.constraints.*;
import java.util.UUID;
import java.time.Instant;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import com.easybase.department.model.Department;
import com.easybase.user.model.enums.UserStatus;
import com.easybase.department.web.dto.DepartmentDTO;

/**
* DTO for incoming User requests.
* Generated by EasyBase Code Generator.
*/
public class UserRequestDTO {
@Email@NotBlank    private String email;
    private String firstName;
    private String lastName;
    private UserStatus status;

    private UUID departmentId;

    public String getEmail() {
return email;
    }

    public void setEmail(String email) {
this.email = email;
    }
    public String getFirstName() {
return firstName;
    }

    public void setFirstName(String firstName) {
this.firstName = firstName;
    }
    public String getLastName() {
return lastName;
    }

    public void setLastName(String lastName) {
this.lastName = lastName;
    }
    public UserStatus getStatus() {
return status;
    }

    public void setStatus(UserStatus status) {
this.status = status;
    }

    public UUID getDepartmentId() {
return departmentId;
    }

    public void setDepartmentId(UUID departmentId) {
this.departmentId = departmentId;
    }
}