package com.easybase.user.web.dto;

import java.time.Instant;
import java.util.UUID;
import java.time.Instant;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import com.easybase.department.model.Department;
import com.easybase.user.model.enums.UserStatus;

/**
* DTO for outgoing User responses.
* Generated by EasyBase Code Generator.
*/
public class UserResponseDTO extends UserDTO {
private Instant createdDate;
private Instant lastModifiedDate;

public Instant getCreatedDate() {
return createdDate;
}

public void setCreatedDate(Instant createdDate) {
this.createdDate = createdDate;
    }

    public Instant getLastModifiedDate() {
return lastModifiedDate;
}

    public void setLastModifiedDate(Instant lastModifiedDate) {
this.lastModifiedDate = lastModifiedDate;
}
}