package com.easybase.user.web.dto;

import java.util.UUID;
import java.time.Instant;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import com.easybase.department.model.Department;
import com.easybase.user.model.enums.UserStatus;
import com.easybase.department.web.dto.DepartmentDTO;

/**
* Base DTO for User data.
* Generated by EasyBase Code Generator.
*/
public class UserDTO {
private UUID id;
private String email;
private String firstName;
private String lastName;
private UserStatus status;

private DepartmentDTO department;

public UUID getId() {
    return id;
}

public void setId(UUID id) {
    this.id = id;
}
public String getEmail() {
    return email;
}

public void setEmail(String email) {
    this.email = email;
}
public String getFirstName() {
    return firstName;
}

public void setFirstName(String firstName) {
    this.firstName = firstName;
}
public String getLastName() {
    return lastName;
}

public void setLastName(String lastName) {
    this.lastName = lastName;
}
public UserStatus getStatus() {
    return status;
}

public void setStatus(UserStatus status) {
    this.status = status;
}

public DepartmentDTO getDepartment() {
    return department;
}
public void setDepartment(DepartmentDTO department) {
    this.department = department;
}
}