package ${entity.packageName};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Import;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

/**
* Main entry point for the ${entity.entity} Spring Boot application.
* Generated by EasyBase Code Generator.
*/
@SpringBootApplication
@EnableJpaRepositories
public class ${entity.entity}Application {

    public static void main(String[] args) {
        SpringApplication.run(${entity.entity}Application.class, args);
    }
}