# Application Configuration for ${entity.entity}
# Generated by EasyBase Code Generator

spring:
    application:
        name: ${entity.module}

    config:
        import: optional:classpath:easybase-config.yml

    jpa:
        hibernate:
            # Disable automatic schema generation - Flyway will handle it
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
        show-sql: true

    # Flyway Migration Configuration
    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration
        table: flyway_schema_history

# Entity-specific settings
easybase:
    entity:
        name: ${entity.entity}
        table: ${entity.table}