package ${entity.baseComponentPackage("repository")};

import ${entity.componentPackage("model")}.${entity.name};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.*;

/**
* Base repository interface for ${entity.name}.
* Generated by EasyBase Code Generator.
*/
public interface ${entity.name}BaseJpaRepository extends JpaRepository<${entity.name}, <#assign primaryKey = entity.primaryKey><#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if>> {
<#if entity.isSoftDeleteEnabled()>
    @Query("SELECT e FROM ${entity.name} e WHERE e.${entity.softDeleteField} = false")
    List<${entity.name}> findAllActive();

    @Query("SELECT e FROM ${entity.name} e WHERE e.id = :id AND e.${entity.softDeleteField} = false")
    Optional<${entity.name}> findByIdActive(@Param("id") <#if primaryKey?has_content>${primaryKey.get().javaType}<#else>Long</#if> id);
</#if>

<#list entity.finders as finder>
    ${finder.methodSignature};
</#list>
}