package ${entity.packageName}.repository;

import ${entity.packageName}.model.${entity.entity};
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
<#-- Import enums -->
<#list entity.fields as field>
<#if field.isEnum()>
import ${entity.packageName}.model.enums.${field.enumClass};
</#if>
</#list>
<#-- Import relationship targets -->
<#list entity.fields as field>
<#if field.isRelationship() && field.targetPackage?? && field.targetPackage?has_content>
import ${field.targetPackage}.${field.target};
</#if>
</#list>

/**
* Repository for ${entity.entity} entities.
* Generated by EasyBase Code Generator.
*/
@Repository
public interface ${entity.entity}Repository extends JpaRepository<${entity.entity}, ${entity.getPrimaryKeyField().javaType}> {
<#-- Finder methods -->
<#if entity.finders??>
<#list entity.finders as finder>
${finder.methodSignature};
</#list>
</#if>
}