-- Migration script for ${entity.name}
-- Generated by EasyBase Code Generator

CREATE TABLE ${entity.fullTableName} (
<#list entity.fields as field>
    ${field.name} ${field.columnDefinition}<#if field_has_next || entity.auditConfig.enabled || entity.isSoftDeleteEnabled()>,</#if>
</#list>
<#if entity.auditConfig.enabled>

    -- Audit fields
    created_date TIMESTAMP<#if entity.isSoftDeleteEnabled() || entity.auditConfig.hasField("modifiedDate") || entity.auditConfig.hasField("createdBy") || entity.auditConfig.hasField("modifiedBy") || entity.auditConfig.hasField("version")>,</#if>
    <#if entity.auditConfig.hasField("modifiedDate")>
        last_modified_date TIMESTAMP<#if entity.isSoftDeleteEnabled() || entity.auditConfig.hasField("createdBy") || entity.auditConfig.hasField("modifiedBy") || entity.auditConfig.hasField("version")>,</#if>
    </#if>
    <#if entity.auditConfig.hasField("createdBy")>
        created_by VARCHAR(255)<#if entity.isSoftDeleteEnabled() || entity.auditConfig.hasField("modifiedBy") || entity.auditConfig.hasField("version")>,</#if>
    </#if>
    <#if entity.auditConfig.hasField("modifiedBy")>
        last_modified_by VARCHAR(255)<#if entity.isSoftDeleteEnabled() || entity.auditConfig.hasField("version")>,</#if>
    </#if>
    <#if entity.auditConfig.hasField("version")>
        version BIGINT DEFAULT 0<#if entity.isSoftDeleteEnabled()>,</#if>
    </#if>
</#if>
<#if entity.isSoftDeleteEnabled()>

    -- Soft delete field
    ${entity.softDeleteField} BOOLEAN DEFAULT FALSE
</#if>
);

-- Create indexes
<#list entity.fields as field>
    <#if field.unique && !field.primaryKey>
        CREATE UNIQUE INDEX idx_${entity.table}_${field.name} ON ${entity.fullTableName}(${field.name});
    </#if>
</#list>

<#list entity.finders as finder>
    <#assign fieldList = []>
    <#list finder.parameters as param>
        <#if param.name?ends_with("Id")>
            <#assign fieldName = param.name?remove_ending("Id")>
            CREATE INDEX idx_${entity.table}_${fieldName}_id ON ${entity.fullTableName}(${fieldName}_id);
        <#else>
            <#assign fieldList = fieldList + [param.name]>
        </#if>
    </#list>
    <#if fieldList?size gt 0>
        CREATE INDEX idx_${entity.table}_${fieldList?join("_")} ON ${entity.fullTableName}(${fieldList?join(", ")});
    </#if>
</#list>