package com.example.product.repository.base;

import com.example.product.model.Product;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import java.util.*;

/**
* Base repository interface for Product.
* Generated by EasyBase Code Generator.
*/
public interface ProductBaseJpaRepository extends JpaRepository<Product, java.util.UUID> {
    @Query("SELECT e FROM Product e WHERE e.deleted = false")
    List<Product> findAllActive();

    @Query("SELECT e FROM Product e WHERE e.id = :id AND e.deleted = false")
    Optional<Product> findByIdActive(@Param("id") java.util.UUID id);

    Optional<Product> findBySku(String sku);
    List<Product> findByNameContaining(String name);
    List<Product> findByPriceRange(Double minPrice, Double maxPrice);
}