package com.example.product.model.base;

import jakarta.persistence.*;
import java.util.Objects;
    import java.util.UUID;
    import jakarta.validation.constraints.NotBlank;
    import jakarta.validation.constraints.Size;
    import jakarta.validation.constraints.NotNull;
    import jakarta.validation.constraints.Min;

/**
* Base entity class for Product.
* Generated by EasyBase Code Generator.
*/
@MappedSuperclass
public class ProductBase {
        @Id
        @GeneratedValue(strategy = GenerationType.IDENTITY)
        @Column(name = "id")
    private java.util.UUID id;
        @Column(name = "name", nullable = false, length = 255)
    private String name;
        @Column(name = "description", length = 1000)
    private String description;
        @Column(name = "price", nullable = false)
    private Double price;
        @Column(name = "sku", nullable = false, unique = true, length = 50)
    private String sku;
        @Column(name = "status")
        @Enumerated(EnumType.STRING)
    private ProductStatus status;

    // Audit fields
    @Column(name = "created_date")
    private java.time.Instant createdDate;

    @Column(name = "last_modified_date")
    private java.time.Instant lastModifiedDate;

        @Column(name = "created_by")
        private String createdBy;


        @Version
        @Column(name = "version")
        private Long version;

    // Soft delete field
    @Column(name = "deleted")
    private boolean deleted = false;

    // Getters and setters
    public java.util.UUID getId() {
    return id;
    }

    public void setId(java.util.UUID id) {
    this.id = id;
    }
    public String getName() {
    return name;
    }

    public void setName(String name) {
    this.name = name;
    }
    public String getDescription() {
    return description;
    }

    public void setDescription(String description) {
    this.description = description;
    }
    public Double getPrice() {
    return price;
    }

    public void setPrice(Double price) {
    this.price = price;
    }
    public String getSku() {
    return sku;
    }

    public void setSku(String sku) {
    this.sku = sku;
    }
    public ProductStatus getStatus() {
    return status;
    }

    public void setStatus(ProductStatus status) {
    this.status = status;
    }

    // Audit getters and setters
    public java.time.Instant getCreatedDate() {
    return createdDate;
    }

    public void setCreatedDate(java.time.Instant createdDate) {
    this.createdDate = createdDate;
    }

    public java.time.Instant getLastModifiedDate() {
    return lastModifiedDate;
    }

    public void setLastModifiedDate(java.time.Instant lastModifiedDate) {
    this.lastModifiedDate = lastModifiedDate;
    }

        public String getCreatedBy() {
        return createdBy;
        }

        public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
        }


        public Long getVersion() {
        return version;
        }

        public void setVersion(Long version) {
        this.version = version;
        }

    // Soft delete getters and setters
    public boolean isDeleted() {
    return deleted;
    }

    public void setDeleted(boolean deleted) {
    this.deleted = deleted;
    }

@Override
public boolean equals(Object o) {
if (this == o) return true;
if (o == null || getClass() != o.getClass()) return false;
ProductBase that = (ProductBase) o;
    return Objects.equals(id, that.id);
}

@Override
public int hashCode() {
    return Objects.hash(id);
}

@Override
public String toString() {
return "Product{" +
    "id=" + id +
    ", " +
    "name=" + name +
    ", " +
    "description=" + description +
    ", " +
    "price=" + price +
    ", " +
    "sku=" + sku +
    ", " +
    "status=" + status +

'}';
}
}