package ${entity.packageName}.web.dto;

import jakarta.validation.constraints.*;
<#list entity.requiredImports as import>
import ${import};
</#list>
<#-- Import enums -->
<#list entity.fields as field>
<#if field.isEnum()>
import ${entity.packageName}.model.enums.${field.enumClass};
</#if>
</#list>
<#-- Import relationship target DTOs -->
<#list entity.fields as field>
<#if field.isRelationship() && field.targetPackage??>
import ${field.targetPackage?substring(0, field.targetPackage?last_index_of("."))}.web.dto.${field.target}DTO;
</#if>
</#list>
<#-- Import List for collections -->
<#assign needsList = false>
<#list entity.fields as field>
<#if field.isRelationship() && (field.relationType == 'OneToMany' || field.relationType == 'ManyToMany')>
<#assign needsList = true>
<#break>
</#if>
</#list>
<#if needsList>
import java.util.List;
</#if>

/**
* DTO for incoming ${entity.entity} requests.
* Generated by EasyBase Code Generator.
*/
public class ${entity.entity}RequestDTO {
<#-- Field declarations with validation -->
<#list entity.fields as field>
<#if !field.isPrimaryKey() && !field.isRelationship()>
<#if field.validation?has_content>
<#list field.validation as validation>
@${validation.type}<#if validation.message??>
(message = "${validation.message}")
    </#if>
    </#list>
    </#if>
    private ${field.javaType} ${field.name};
    </#if>
    </#list>

    <#-- Relationship IDs or DTOs -->
    <#list entity.fields as field>
    <#if field.isRelationship()>
    <#if field.relationType == 'ManyToOne' || field.relationType == 'OneToOne'>
    private UUID ${field.name}Id;
    <#else>
    private List<UUID> ${field.name}Ids;
    </#if>
    </#if>
    </#list>

    <#-- Getters and Setters -->
    <#list entity.fields as field>
    <#if !field.isPrimaryKey() && !field.isRelationship()>
    public ${field.javaType} get${field.name?cap_first}() {
return ${field.name};
    }

    public void set${field.name?cap_first}(${field.javaType} ${field.name}) {
this.${field.name} = ${field.name};
    }
    </#if>
    </#list>

    <#-- Relationship ID getters and setters -->
    <#list entity.fields as field>
    <#if field.isRelationship()>
    <#if field.relationType == 'ManyToOne' || field.relationType == 'OneToOne'>
    public UUID get${field.name?cap_first}Id() {
return ${field.name}Id;
    }

    public void set${field.name?cap_first}Id(UUID ${field.name}Id) {
this.${field.name}Id = ${field.name}Id;
    }
    <#else>
    public List<UUID> get${field.name?cap_first}Ids() {
return ${field.name}Ids;
    }

    public void set${field.name?cap_first}Ids(List<UUID> ${field.name}Ids) {
this.${field.name}Ids = ${field.name}Ids;
    }
    </#if>
    </#if>
    </#list>
}